## IMPORTING LIBRARIES

In [1]:
import seaborn as sns
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime
import plotly.io as pio
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from plotly.offline import plot

## OPENING DATASET

In [2]:
df = pd.read_csv('Speed+Dating+Data.csv', encoding='ISO-8859-1')
print(df.shape)
df.head()

(8378, 195)

,iid,id,gender,idg,condtn,wave,round,position,positin1,order,...,attr3_3,sinc3_3,intel3_3,fun3_3,amb3_3,attr5_3,sinc5_3,intel5_3,fun5_3,amb5_3
0,1,1.0,0,1,1,1,10,7,NaN,4,...,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
1,1,1.0,0,1,1,1,10,7,NaN,3,...,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
2,1,1.0,0,1,1,1,10,7,NaN,10,...,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
3,1,1.0,0,1,1,1,10,7,NaN,5,...,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
4,1,1.0,0,1,1,1,10,7,NaN,7,...,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN

In [3]:
df.describe(include='all')

,iid,id,gender,idg,condtn,wave,round,position,positin1,order,...,attr3_3,sinc3_3,intel3_3,fun3_3,amb3_3,attr5_3,sinc5_3,intel5_3,fun5_3,amb5_3
count,8378.000000,8377.000000,8378.000000,8378.000000,8378.000000,8378.000000,8378.000000,8378.000000,6532.000000,8378.000000,...,3974.000000,3974.000000,3974.000000,3974.000000,3974.000000,2016.000000,2016.000000,2016.000000,2016.000000,2016.000000
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,283.675937,8.960248,0.500597,17.327166,1.828837,11.350919,16.872046,9.042731,9.295775,8.927668,...,7.240312,8.093357,8.388777,7.658782,7.391545,6.810020,7.615079,7.932540,7.155258,7.048611
std,158.583367,5.491329,0.500029,10.940735,0.376673,5.995903,4.358458,5.514939,5.650199,5.477009,...,1.576596,1.610309,1.459094,1.744670,1.961417,1.507341,1.504551,1.340868,1.672787,1.717988
min,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,5.000000,1.000000,1.000000,1.000000,...,2.000000,2.000000,3.000000,2.000000,1.000000,2.000000,2.000000,4.000000,1.000000,1.000000
25%,154.000000,4.000000,0.000000,8.000000,2.000000,7.000000,14.000000,4.000000,4.000000,4.000000,...,7.000000,7.000000,8.000000,7.000000,6.000000,6.000000,7.000000,7.000000,6.000000,6.000000
50%,281.000000,8.000000,1.000000,16.000000,2.000000,11.000000,18.000000,8.000000,9.000000,8.000000,...,7.000000,8.000000,8.000000,8.000000,8.000000,7.000000,8.000000,8.000000,7.000000,7.000000
75%,407.000000,13.000000,1.000000,26.000000,2.000000,15.000000,20.000000,13.000000,14.000000,13.000000,...,8.000000,9.000000,9.000000,9.000000,9.000000,8.000000,9.000000,9.000000,8.000000,8.000000
max,552.000000,22.000000,1.000000,44.000000,2.000000,21.000000,22.000000,22.000000,22.000000,22.000000,...,12.000000,12.000000,12.000000,12.000000,12.000000,10.000000,10.000000,10.000000,10.000000,10.000000

In [4]:
df['gender'].value_counts()

1    4194
0    4184
Name: gender, dtype: int64

## Processing of missing values

In [60]:
df_test = df[:10]

In [65]:
df_test.iloc[:,100:].columns

Index(['intel', 'fun', 'amb', 'shar', 'like', 'prob', 'met', 'match_es',
       'attr1_s', 'sinc1_s', 'intel1_s', 'fun1_s', 'amb1_s', 'shar1_s',
       'attr3_s', 'sinc3_s', 'intel3_s', 'fun3_s', 'amb3_s', 'satis_2',
       'length', 'numdat_2', 'attr7_2', 'sinc7_2', 'intel7_2', 'fun7_2',
       'amb7_2', 'shar7_2', 'attr1_2', 'sinc1_2', 'intel1_2', 'fun1_2',
       'amb1_2', 'shar1_2', 'attr4_2', 'sinc4_2', 'intel4_2', 'fun4_2',
       'amb4_2', 'shar4_2', 'attr2_2', 'sinc2_2', 'intel2_2', 'fun2_2',
       'amb2_2', 'shar2_2', 'attr3_2', 'sinc3_2', 'intel3_2', 'fun3_2',
       'amb3_2', 'attr5_2', 'sinc5_2', 'intel5_2', 'fun5_2', 'amb5_2',
       'you_call', 'them_cal', 'date_3', 'numdat_3', 'num_in_3', 'attr1_3',
       'sinc1_3', 'intel1_3', 'fun1_3', 'amb1_3', 'shar1_3', 'attr7_3',
       'sinc7_3', 'intel7_3', 'fun7_3', 'amb7_3', 'shar7_3', 'attr4_3',
       'sinc4_3', 'intel4_3', 'fun4_3', 'amb4_3', 'shar4_3', 'attr2_3',
       'sinc2_3', 'intel2_3', 'fun2_3', 'amb2_3', 'shar2_3', 'attr3_3',
       'sinc3_3', 'intel3_3', 'fun3_3', 'amb3_3', 'attr5_3', 'sinc5_3',
       'intel5_3', 'fun5_3', 'amb5_3'],
      dtype='object')

In [59]:
df_test = df_test.fillna(df.mean())
df_test

C:\Users\galus\AppData\Local\Temp\ipykernel_19280\1588382658.py:1: FutureWarning:

The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.

,iid,id,gender,idg,condtn,wave,round,position,positin1,order,...,attr3_3,sinc3_3,intel3_3,fun3_3,amb3_3,attr5_3,sinc5_3,intel5_3,fun5_3,amb5_3
0,1,1.0,0,1,1,1,10,7,9.295775,4,...,5.0,7.0,7.0,7.0,7.0,6.81002,7.615079,7.93254,7.155258,7.048611
1,1,1.0,0,1,1,1,10,7,9.295775,3,...,5.0,7.0,7.0,7.0,7.0,6.81002,7.615079,7.93254,7.155258,7.048611
2,1,1.0,0,1,1,1,10,7,9.295775,10,...,5.0,7.0,7.0,7.0,7.0,6.81002,7.615079,7.93254,7.155258,7.048611
3,1,1.0,0,1,1,1,10,7,9.295775,5,...,5.0,7.0,7.0,7.0,7.0,6.81002,7.615079,7.93254,7.155258,7.048611
4,1,1.0,0,1,1,1,10,7,9.295775,7,...,5.0,7.0,7.0,7.0,7.0,6.81002,7.615079,7.93254,7.155258,7.048611
5,1,1.0,0,1,1,1,10,7,9.295775,6,...,5.0,7.0,7.0,7.0,7.0,6.81002,7.615079,7.93254,7.155258,7.048611
6,1,1.0,0,1,1,1,10,7,9.295775,1,...,5.0,7.0,7.0,7.0,7.0,6.81002,7.615079,7.93254,7.155258,7.048611
7,1,1.0,0,1,1,1,10,7,9.295775,2,...,5.0,7.0,7.0,7.0,7.0,6.81002,7.615079,7.93254,7.155258,7.048611
8,1,1.0,0,1,1,1,10,7,9.295775,8,...,5.0,7.0,7.0,7.0,7.0,6.81002,7.615079,7.93254,7.155258,7.048611
9,1,1.0,0,1,1,1,10,7,9.295775,9,...,5.0,7.0,7.0,7.0,7.0,6.81002,7.615079,7.93254,7.155258,7.048611

1.0     552
2.0     552
6.0     552
4.0     547
5.0     547
3.0     541
7.0     505
8.0     505
10.0    480
9.0     479
12.0    382
11.0    382
14.0    372
13.0    357
15.0    348
16.0    319
17.0    253
18.0    237
19.0    178
20.0    160
21.0     86
22.0     43
Name: id, dtype: int64

## Let's try to determine what are the least attractive attributes in a male partner

In [52]:

fem_score_list = ['attr1_1',  'sinc1_1', 'intel1_1', 'fun1_1', 'amb1_1', 'shar1_1']
df_female = df[df['gender'] == 0]
df_female[fem_score_list].value_counts()
# len(df_female[fem_score_list].value_counts().values)

attr1_1  sinc1_1  intel1_1  fun1_1  amb1_1  shar1_1
20.00    20.00    20.00     10.00   10.00   20.00      70
                            20.00   10.00   10.00      66
                            15.00   15.00   10.00      66
                            20.00   20.00   0.00       52
10.00    20.00    20.00     20.00   20.00   10.00      50
                                                       ..
30.00    10.00    10.00     30.00   10.00   10.00       6
25.00    0.00     25.00     25.00   0.00    25.00       6
6.67     20.00    20.00     17.78   20.00   15.56       5
12.77    19.15    17.02     17.02   14.89   19.15       5
18.18    22.73    18.18     13.64   13.64   13.64       5
Length: 234, dtype: int64